### ISSUE TITLE
[ZF3] FlashMessenger: sort by datetime / multiple tagging

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zendframework#7161]
Since the flashMessenger uses namespaces to group the messages, its impossible to sort the messages just by date.

I suggest to remove that limitation. Instead of grouping it in different arrays, maybe it would be better to store them in a single array.

To achieve the different types, maybe we could do that over "tagging". This could also enable mutliple tagging/routing to the right place...

**Comment by manuakasam** [comment]
I'm against removing the namespaces because it eases grouping messages a lot. There's been many cases where I've used Namespaces on FlashMessages and found the feature incredibly useful.

However it shouldn't be this difficult to rewrite to have it ordered by date (per namespace though!)

Right now the code is:
```
$container->{$namespace}->push($message);
```

All the change required would be

```
$time = microtime(true) * 1000;
$container->{$namespace}->offsetSet($time, $message);
```

This however would dare a risk of overwriting messages (though quite low).

I'd rather see an additional FlashMessenger implementation like TimedFlashMessenger that simply does things a bit different. Thoughts?

**Comment by RalfEggert** [comment]
Should be marked for ZF3 milestone, shouldn't it?

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mvc/issues/178
