### ISSUE TITLE
BootstrapListenerInterface compatibility error

### ISSUE THREAD

**Issue by semihs** [zendframework/zendframework#7724]
throws fatal error while BootstrapListenerInterface implemented.
I am not sure, my design right ?

    use Zend\ModuleManager\Feature\BootstrapListenerInterface;
    use Zend\Mvc\MvcEvent;

    /**
     * Class Module
     * @package Application
     */
    class Module implements ConfigProviderInterface, BootstrapListenerInterface
    {
        /**
         * @var string
         */
        const VERSION = '1.0.0dev';

        /**
         * @param MvcEvent $event
         */
        public function onBootstrap(MvcEvent $event)
        {
        }
    }

Fatal error: Declaration of Application\Module::onBootstrap(Zend\Mvc\MvcEvent $event) must be compatible with Zend\ModuleManager\Feature\BootstrapListenerInterface::onBootstrap(Zend\EventManager\EventInterface $e) in module/Application/src/Module.php on line 14

**Comment by jeandormehl** [comment]
Hello @semihs . Change the following...

In use block:

`- use Zend\Mvc\MvcEvent`
`+ use Zend\EventManager\EventInterface`

onBootstrap function:

`+ public function onBootstrap(EventInterface $event)
{
`

**Comment by semihs** [comment]
There are not implemented methods in MvcEvent. for example application property. 
No problem but does not provide hinting

**Comment by weierophinney** [comment]
I've just looked, because usually specify MvcEvent in implementations I write. The reason that works is... I don't implement the interface directly. In every case, the listeners look for either implementations of the interface *or* that the module class implements the required method. 

The point is: if you want the typehinting in your IDE, drop the implementation at the class level, and update your method to use the expected event class.

(We cannot change the typehint in the interface at this point as it would break BC.)
