### ISSUE TITLE
Composer Resolution

### ISSUE THREAD

**Issue by wandersonwhcr** [zendframework/zendframework#7753]
Hello,

I'm trying to install Zend Framework 2.5.2 with Composer and after downloading, Composer throws a checksum error, resolving the package to:

https://packages.zendframework.com/composer/zendframework-zendframework-2.5.2-3accd3.zip

Unzipping this file, it's empty.

Any ideas?

**Comment by Ocramius** [comment]
zendframework 2.5 is indeed most probably an empty package, since 2.5.0 is the version where the component split was applied. Unsure if that's a build tool issue. @wandersonwhcr I would simply suggest removing `packages.zendframework.com` from your `composer.json`, since `packagist.org` is now a stable and reliable source of truth for package versions.

**Comment by wandersonwhcr** [comment]
ty @Ocramius, I just removed my `composer.lock` and removed the `packages.zendframework.com` from `repositories` in my `composer.json` and it works.
