### ISSUE TITLE
Status of ZF3 / Trends / MVC

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#7755]
I use ZF2 and now 3 since it was released. I observe the status and news about the framework regularly, in the last time however I recognized that the activity of the framework decreased in some way.
I want you ask, the contributors or someone who knows more, unobtrusive about the plans of ZF3 or maybe moving trends which affects the ZF3 strategy / time of life.
I know **node.js** is on a never ending trend, lot of frontend stuff is moving away from backend, which is definitely affects the backend responsibilities.
I really like the ZF3 architecture because we use it in an extremely complex application.

However I really would like to see that the framework and ecosystem get developer further.
Especially the MVC and it component parts was left lying.
So:

**Is ZF3 just to complex for most of the use cases or what exactly is going on with it?**

**Are there any further long-term plans for the framework / what's the vision?**

**Comment by Ocramius** [comment]
> I use ZF2 and now 3 since it was released. I observe the status and news about the framework regularly, in the last time however I recognized that the activity of the framework decreased in some way.

The activity on the components increased by a huge lot - you are most probably not following all repositories, but we have loads of releases every week, and since the split, code is much more manageable.

 > I want you ask, the contributors or someone who knows more, unobtrusive about the plans of ZF3 or maybe moving trends which affects the ZF3 strategy / time of life.
 > I know **node.js** is on a never ending trend, lot of frontend stuff is moving away from backend, which is definitely affects the backend responsibilities.
 > I really like the ZF3 architecture because we use it in an extremely complex application.

If you are worried about the MVC architecture, you must track https://github.com/zendframework/zend-mvc, which is the package that handles the currently enstablished mvc-event/route/controller/view-model/view approach. Specifically, check the releases: https://github.com/zendframework/zend-mvc/releases for anything that may break things for you.

MVC 3.x is currently stable and we're not going to change its public API, so you can safely keep relying on it.

 > However I really would like to see that the framework and ecosystem get developer further. Especially the MVC and it component parts was left lying.

As mentioned above, it's not left lying - we got you covered.

 > Is ZF3 just to complex for most of the use cases or what exactly is going on with it?

You are not watching the components, which is where the work is happening, and therefore you don't see any changes in `zendframework/zendframework`, which now is just a meta-package with only some defined dependencies.

 > Are there any further long-term plans for the framework / what's the vision?

 * Releases will keep going on the single packages. Meta-package may be updated on major version bumps of the component packages (only very few of those happening).
 * MVC component is staying as-is, with just upgrades to latest dependencies as these changes land in the other components

Hope that clarifies everything.
