### ISSUE TITLE
I want to install zend 2 in my pc. but each time i download it download zend 3. Please help me with this  issue.

### ISSUE THREAD

**Issue by Nilayshah123** [zendframework/zendframework#7766]

**Comment by weierophinney** [comment]
I'm assuming you're using Composer, as we do not provide download packages of Zend Framework 3 in any other fashion.

What version of ZF2 are you wanting? The LTS (2.4)? or latest?

In either case, you will need to provide a version constraint when calling `composer require`. As examples:

```bash
# Require the LTS (2.4) series:
$ composer require "zendframework/zendframework:~2.4.0"
# Require any 2.4 or later version, but not 3.X:
$ composer require "zendframework/zendframework:^2.4"
```

The `~` constraint pins to the latest release of the same priority, where the priority is determined by the number of decimals. If you pin using MAJOR.MINOR, it will grab the latest within the MAJOR series; if you pin using MAJOR.MINOR.PATCH, it will grab the latest within the MINOR series. As such, the first example will currently grab version 2.4.11. If you want to get 2.4.11 and any later 2.4 release, you'd use `~2.4.11` as your constraint.

The `^` constraints to the latest release in the MAJOR series from the release specified forwards, which is why the last one will currently install 2.5.3. If you want to get 2.5.3 and forwards, you'd specify `^2.5.3`.

If you are manually specifying the requirement in your `composer.json`, use the above constraints for the `zendframework/zendframework` package.

For more information, [read the Composer documentation on version constraints](https://getcomposer.org/doc/articles/versions.md).
