### ISSUE TITLE
[Question] Why so many redundancies?

### ISSUE THREAD

**Issue by Beatsleigher** [zendframework/zendframework#7767]
I'm trying to wrap my head around this (frankly mess of a) framework, and there are a lot of things bugging me, which is hindering me from creating the quality of code I desire.
Apart from the fact that the framework is inconsistent all the way through, why are there so many redundancies? 
Why does a framework need 100 different RuntimeExceptions, instead of having one RuntimeException in a standard namespace like other frameworks?

From what I can tell, the classes are identical except for the namepace. Why was this design choice made, instead of having the exceptions in a single namespace, or at the root of the appropriate namespaces, such as in .Net/Java? 

In .Net, the RuntimeException class is in the System namespace, which is automatically included, and in Java the RuntimeException is in the java.lang.* namespace, which is also automatically included. 

Thanks in advance!

**Comment by Ocramius** [comment]
> Why does a framework need 100 different RuntimeExceptions, instead of having one RuntimeException in a standard namespace like other frameworks?

Catching component-specific exceptions is extremely important when dealing with specific failures. We even use component-wide marker interfaces (`ExceptionInterface` in the namespace of the component, for example, and also sub-components of each component).

 > From what I can tell, the classes are identical except for the namepace. Why was this design choice made, instead of having the exceptions in a single namespace, or at the root of the appropriate namespaces, such as in .Net/Java?

It is a design choice: if you send a patch for new functionality that may fail (throw exceptions) in new and specific ways, you *will* be asked to provide custom exception types.

 > In .Net, the RuntimeException class is in the System namespace, which is automatically included, and in Java the RuntimeException is in the java.lang.* namespace, which is also automatically included.

These are base exceptions, and they are too generic. Throwing those directly is also not endorsed in Java or .NET, as you are making it harder for the consumer to distinguish the possible failure types, as well as the implementor for making the possible thrown exceptions terrible to document (they all look the same).

The exceptions in the ZF components still extend from the base exceptions provided by PHP itself, but the additional type information provided is extremely valuable, and should be provided whenever possible.

In addition to that, exceptions are for exceptional scenarios, so the performance impact of the additional autoloading is negligible.

Hope this clarifies your question!

**Comment by Ocramius** [comment]
Ah, I forgot one GINORMOUS and obvious advantage: your logs include the exception type as well as the message! 

That makes it extremely trivial to understand where something went bad ;-)

**Comment by Beatsleigher** [comment]
I guess that makes sense enough to appreciate the decision. 

Cheers!

**Comment by unkind** [comment]
@Ocramius the thing is most of the exceptions are unchecked (in terms of Java and .NET), you don't need to specify them in the `@throws`, so client shouldn't be aware of them at all. They are meant to be catched like `\Exception $e` or `\Throwable $e` to prevent crash of the whole program.

> We even use component-wide marker interfaces (ExceptionInterface in the namespace of the component, for example, and also sub-components of each component).

Could you provide an example when you need it and you can't replace it with `catch (\Exception $e)`?

For example, I very actively use this library: https://github.com/beberlei/assert In most cases, this tool throws the same type of exception, because it doesn't matter: this exception just means that you have to fix the code, there is no need to "recover" in some different way. If you try to call `new KelvinTemperature(-1)`, then you have a bug in your code, it makes no sense.

**Comment by Ocramius** [comment]
Also, yes, exceptions should be declared via `@throws` whenever possible,
but PHP doesn't help much in distinguishing or forcing checked/unchecked.

Heck, we still have those shitty warning mechanics.

On 14 Jun 2017 4:28 p.m., "Marco Pivetta" <ocramius@gmail.com> wrote:

> Could you provide an example when you need it and you can't replace it
with catch (\Exception $e)?

Deciding whether a configuration is broken (for example in the DI
container) versus whether the connection to the DB failed during service
initialisation. You will get a `ServiceNotFoundException` or a
`ServiceNotCreatedException` makes a load of difference.

**Comment by unkind** [comment]
> You will get a `ServiceNotFoundException` or a `ServiceNotCreatedException` makes a load of difference.

Yeah. `ServiceNotFoundException` looks like checked one, but who needs to catch `ServiceNotCreatedException`? This config is broken, fix it.

**Comment by Ocramius** [comment]
You need to catch it for retriable operations, such as re-queuing an
operation for later execution if your backend is busy.

**Comment by Ocramius** [comment]
Also, note that "handling" exceptions is *RARE*. This is a general purpose
component framework, and therefore the use-case scenarios are extremely
huge in amount.

This does not mean that you, in your opinionated application and business
domain will have to implement exception handling this way, but if you use a
library you should really expect this kind of fine-grained support by the
technical layer.

On 14 Jun 2017 4:40 p.m., "Marco Pivetta" <ocramius@gmail.com> wrote:

You need to catch it for retriable operations, such as re-queuing an
operation for later execution if your backend is busy.

**Comment by unkind** [comment]
> You need to catch it for retriable operations, such as re-queuing an
operation for later execution if your backend is busy.

Note that I ask difference with `catch (\Exception $e)` which is suitable for this purpose too (even better, because it covers all type of errors):
```php
try {
    $foo->bar();
} catch (SomeCheckedException $e) {
    ; // OK, probably its' fine.
} catch (\Throwable $e) {
    // Not fine, we need to requeue operation.
}
```

**Comment by Ocramius** [comment]
You usually do the opposite: only re-queue for a certain subset of exceptions. Still, the point stands: more granular types help *a lot* in failure handling scenarios. Having or not having them is a question of few minutes of work, so it's a no-brainer: if you write a library, each failure type should have its own specific language-level defined type.

**Comment by nesl247** [comment]
You mention that catching `\Exception` is even better because it covers all types of errors. This is something you want to avoid. You should almost never catch all exceptions. The reason is, how can you handle all types of exceptions in one catch block? Each exception probably needs to be handled differently. What happens when a new exception is added that needs to be logged or something? You won't know because your code is catching all exceptions.

Always try to be explicit with the exceptions you catch. Otherwise you end up with a lot of side-effects.

**Comment by unkind** [comment]
> The reason is, how can you handle all types of exceptions in one catch block?

You don't "handle" it, you just prevent crash of you whole program and log the exception, e.g. front controller, console application, some queue consumers, event listeners (especially, if you have concept of async event listeners), etc. Obviously, you are not able to specify concrete type because you don't know it.

**Comment by weierophinney** [comment]
@unkind —

> We know that "something" is broken in FooBarComponent and it gives us no benefit

I disagree. Many times we will be using components that consume other components, which consume other components, and so on down the line, and a generic exception makes tracking this information more difficult. As an example, let's say I have a repository class that composes an input filter, and delegates to Doctrine to perform database operations, but also does some caching on top of all of this. If each of these raise generic language-level exceptions, I know absolutely nothing from seeing just the exception type, and generally speaking, even the message doesn't contain enough information to go on. Was the exception due to an error in my input filters? or my caching layer? or in Doctrine? I have to dive into the exception details (file and line) to get an idea of what threw the exception, and sometimes that doesn't even make the component that threw it clear — particularly if somewhere down the line, I caught and re-threw, embedding the original exception as a previous exception.

On top of all this, what you detail in your comment is using a global exception handler. This is fine. However, sometimes I may want to _recover gracefully_. Sometimes I know that code I invoke will raise an exception, and I can still continue processing, or branch my logic as a result. So, now I have a `try/catch` block... only what do I catch? If everything is a language level exception, I now also need to know the expected messages and/or codes they may return — and these are things that may actually change from version to version of a component, making such lookups brittle:

```php
try {
    $execute->someCode();
} catch (RuntimeException $e) {
    if (preg_match('/some string I might expect/', $e->getMessage()) {
        // handle gracefully
    } elseif (preg_match('/some other string I might expect/', $e->getMessage()) {
        // also handle gracefully
    } else {
        // don't know how to handle this!
        throw $e;
    }
}
```

The thing is, PHP already provides a much more efficient way to do this, by allowing you to provide your own exception types, and use multiple catches:

```php
try {
    $execute->someCode();
} catch (InputFilter\ExceptionInterface $e) {
    // Catch any input filter exception and handle gracefully
} catch (Some\Component\Exception\SpecificCaseException $e) {
    // Catch a specific exception from a component
}
```

Having specific types makes these try/catch blocks trivial, and makes it more clear what sort of errors you can recover gracefully from. Having a component-level exception marker interface allows you to catch any exception from a given component; having specific exceptions allows more granular catching. Since each of these extend existing SPL exception types, which derive from the PHP exception type hierarchy, you can also go as general as you want.

The point is, **you** may not need this sort of granularity, but **many** do, and there are plenty of good reasons to provide it. If you don't need it, continue catching `\Exception`. Those of us that want more granularity will be happy that we can do so.

**Comment by unkind** [comment]
OK, we just gonna repeat the same arguments as we did in PSR-11 discussion about `ContainerExceptionInterface`. 😕

**Comment by Ocramius** [comment]
Which, by the way, is successfully split into service-not-found and a more
generic container-exception. That separation is already used in the wild,
and makes things easier for consumers 😋

**Comment by unkind** [comment]
Let's read the [source](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md#12-exceptions):

> `Exceptions directly thrown by the container SHOULD implement the Psr\Container\ContainerExceptionInterface`
> ...
> `@throws` ContainerExceptionInterface Error while retrieving the entry.

How does it make things more clear for consumers? I have no guarantee that error would be wrapped into `ContainerExceptionInterface`: it says "SHOULD" and only for "directly thrown" exceptions; and it says nothing but "Error while retrieving the entry". So, if I really want to know whether I succeed to get service or not, I have to catch more generic `\Exception`.  You might say that I probably know what does it mean if I look in the container implementation, but it defeats the purpose of the PSR.

> That separation is already used in the wild

If majority do X, then X is valid? :)

**Comment by Ocramius** [comment]
> If majority do X, then X is valid? :)

It simply means that the use-case is there and works. If you feel like
keeping denying it for the sake of it (and tbh, I still don't understand
what your point is), feel free to do so.
